let iconList = [
  { className: 'calendar' },
  { className: 'card-blue2' },
  { className: 'card-dark-blue2' },
  { className: 'card-dark-blue1' },
  { className: 'card-green1' },
  { className: 'card-green2' },
  { className: 'dashboard-card-blue1' },
  { className: 'icon-check-box-h' },
  { className: 'icon-check-box-n' },
  { className: 'icon-check-box-p' },
  { className: 'icon-check-box' },
  { className: 'manergement-abnormal-machine' },
  { className: 'manergement-devicelist' },
  { className: 'manergement-eventlist' },
  { className: 'manergement-eventtrash' },
  { className: 'manergement-gatewaymanagement' },
  { className: 'manergement-modelmanagement' },
  { className: 'manergement-rulesettings' },
  { className: 'manergement-sensor-overview' },
  { className: 'navigatuion-drawer' },
  { className: 'rectangle-9163' },
  { className: 'toggle-unselect-d' },
  { className: 'toggle-unselect-h' },
  { className: 'toggle-unselect-n' },
  { className: 'toggle-unselect-p' },
  { className: 'user-icon' },
];

export default iconList;
