let iconList = [
  { className: 'aiot-logo-white.png' },
  { className: 'asus-iot-phm-dashboard-card-blue-1-1' },
  { className: 'asus-iot-phm-dashboard-card-blue-1-2' },
  { className: 'asus-iot-phm-dashboard-card-darkblue-1-1' },
  { className: 'asus-iot-phm-dashboard-card-dark-blue-1-2' },
  { className: 'asus-iot-phm-dashboard-card-green-1-1' },
  { className: 'asus-iot-phm-dashboard-card-green-1-2' },
  { className: 'asus-iot-phm-dashboard-icon-check-box-d' },
  { className: 'asus-iot-phm-dashboard-icon-check-box-h' },
  { className: 'asus-iot-phm-dashboard-icon-check-box-n' },
  { className: 'asus-iot-phm-dashboard-icon-check-box-p' },
  { className: 'asus-iot-phm-dashboard-icon-toggle-unselect-d' },
  { className: 'asus-iot-phm-dashboard-icon-toggle-unselect-h' },
  { className: 'asus-iot-phm-dashboard-icon-toggle-unselect-n' },
  { className: 'asus-iot-phm-dashboard-icon-toggle-unselect-p' },
  { className: 'asus-iot-phm-icon-search' },
  { className: 'asus-iot-phm-sider-icon-device-manergement-devicelist' },
  { className: 'asus-iot-phm-sider-icon-device-manergement-gatewaymanagement' },
  { className: 'asus-iot-phm-sider-icon-event-manergement-abnormal-machine' },
  { className: 'asus-iot-phm-sider-icon-event-manergement-eventlist' },
  { className: 'asus-iot-phm-sider-icon-event-manergement-eventtrash' },
  { className: 'asus-iot-phm-sider-icon-event-manergement-sensor-overview' },
  { className: 'asus-iot-phm-sider-icon-rules-manergement-modelmanagement' },
  { className: 'asus-iot-phm-sider-icon-rules-manergement-rulesettings' },
  { className: 'asus-iot-phm-user-icon' },
  { className: 'calendar' },
  { className: 'navigatuion-drawer' },
  { className: 'rectangle-9163' },
];

export default iconList;
