let iconList = [
  { className: 'aiot-logo-white.png' },
  { className: 'asus-iot-phm-dashboard-card-blue-1-1' },
  { className: 'asus-iot-phm-dashboard-card-blue-1-2' },
  { className: 'asus-iot-phm-dashboard-card-darkblue-1-1' },
  { className: 'asus-iot-phm-dashboard-card-dark-blue-1-2' },
  { className: 'asus-iot-phm-dashboard-card-green-1-1' },
  { className: 'asus-iot-phm-dashboard-card-green-1-2' },
  { className: 'asus-iot-phm-dashboard-icon-check-box-d' },
  { className: 'asus-iot-phm-dashboard-icon-check-box-h' },
  { className: 'asus-iot-phm-dashboard-icon-check-box-n' },
  { className: 'asus-iot-phm-dashboard-icon-check-box-p' },
  { className: 'asus-iot-phm-dashboard-icon-toggle-unselect-d' },
  { className: 'asus-iot-phm-dashboard-icon-toggle-unselect-h' },
  { className: 'asus-iot-phm-dashboard-icon-toggle-unselect-n' },
  { className: 'asus-iot-phm-dashboard-icon-toggle-unselect-p' },
  { className: 'search' },
  { className: 'devicelist' },
  { className: 'gatewaymanagement' },
  { className: 'abnormal-machine' },
  { className: 'eventlist' },
  { className: 'eventtrash' },
  { className: 'sensor-overview' },
  { className: 'modelmanagement' },
  { className: 'rulesettings' },
  { className: 'asus-iot-phm-user-icon' },
  { className: 'calendar' },
  { className: 'navigatuion-drawer' },
  { className: 'rectangle-9163' },
  { className: 'click' },
  { className: 'exit' },
  { className: 'restore' },
  { className: 'trash' },
];

export default iconList;
